apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sample-site-tls
  namespace: trialnamespace
spec:
  secretName: tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: sample.terrasofthq.com
  dnsNames:
    - sample.terrasofthq.com
